/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jpanel;

/**
 *
 * @author Admin
 */
public class AuthorListPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthorListPanel
     */
    public AuthorListPanel() {
        initComponents();
        setBounds(0, 0,1288, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTable = new javax.swing.JPanel();
        jScrollPaneAuthorTable = new javax.swing.JScrollPane();
        rsAuthorTable = new rojeru_san.complementos.RSTableMetro();
        jPanelAuthor = new javax.swing.JPanel();
        jLabelAuthorTitle = new javax.swing.JLabel();
        jPanelAuthorID = new javax.swing.JPanel();
        jLabelAuthorID = new javax.swing.JLabel();
        jTextFieldAuthorID = new app.bolivia.swing.JCTextField();
        jPanelAuthorName = new javax.swing.JPanel();
        jLabelAuthorName = new javax.swing.JLabel();
        jTextFieldAuthorName = new app.bolivia.swing.JCTextField();
        jPanelAuthorPlace = new javax.swing.JPanel();
        jLabelAuthorPlace = new javax.swing.JLabel();
        jTextFieldAuthorPlace = new app.bolivia.swing.JCTextField();
        jPanelAuthorButton = new javax.swing.JPanel();
        rsButtonAuthorAdd = new rojeru_san.complementos.RSButtonHover();
        rsButtonAuthorClear = new rojeru_san.complementos.RSButtonHover();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1230, 730));
        setPreferredSize(new java.awt.Dimension(1230, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTable.setBackground(new java.awt.Color(255, 255, 255));

        rsAuthorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneAuthorTable.setViewportView(rsAuthorTable);

        jPanelAuthor.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAuthorTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelAuthorTitle.setText("Author List");

        jPanelAuthorID.setBackground(new java.awt.Color(255, 255, 204));

        jLabelAuthorID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAuthorID.setText("Author ID");

        jTextFieldAuthorID.setText("jCTextField1");
        jTextFieldAuthorID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelAuthorIDLayout = new javax.swing.GroupLayout(jPanelAuthorID);
        jPanelAuthorID.setLayout(jPanelAuthorIDLayout);
        jPanelAuthorIDLayout.setHorizontalGroup(
            jPanelAuthorIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAuthorIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAuthorID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAuthorIDLayout.createSequentialGroup()
                        .addComponent(jLabelAuthorID)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAuthorIDLayout.setVerticalGroup(
            jPanelAuthorIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAuthorID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldAuthorID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelAuthorName.setBackground(new java.awt.Color(255, 255, 204));

        jLabelAuthorName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAuthorName.setText("Author Name");

        jTextFieldAuthorName.setText("jCTextField1");
        jTextFieldAuthorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelAuthorNameLayout = new javax.swing.GroupLayout(jPanelAuthorName);
        jPanelAuthorName.setLayout(jPanelAuthorNameLayout);
        jPanelAuthorNameLayout.setHorizontalGroup(
            jPanelAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAuthorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAuthorNameLayout.createSequentialGroup()
                        .addComponent(jLabelAuthorName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAuthorNameLayout.setVerticalGroup(
            jPanelAuthorNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAuthorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAuthorName, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        jPanelAuthorPlace.setBackground(new java.awt.Color(255, 255, 204));

        jLabelAuthorPlace.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAuthorPlace.setText("Author Place");

        jTextFieldAuthorPlace.setText("jCTextField1");
        jTextFieldAuthorPlace.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelAuthorPlaceLayout = new javax.swing.GroupLayout(jPanelAuthorPlace);
        jPanelAuthorPlace.setLayout(jPanelAuthorPlaceLayout);
        jPanelAuthorPlaceLayout.setHorizontalGroup(
            jPanelAuthorPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorPlaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAuthorPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAuthorPlaceLayout.createSequentialGroup()
                        .addComponent(jLabelAuthorPlace)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldAuthorPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAuthorPlaceLayout.setVerticalGroup(
            jPanelAuthorPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorPlaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAuthorPlace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAuthorPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        rsButtonAuthorAdd.setActionCommand("rsButtonAuthorAdd");
        rsButtonAuthorAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rsButtonAuthorAdd.setLabel("Add/Edit");

        rsButtonAuthorClear.setActionCommand("rsButtonAuthorClear");
        rsButtonAuthorClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rsButtonAuthorClear.setLabel("Clear");

        javax.swing.GroupLayout jPanelAuthorButtonLayout = new javax.swing.GroupLayout(jPanelAuthorButton);
        jPanelAuthorButton.setLayout(jPanelAuthorButtonLayout);
        jPanelAuthorButtonLayout.setHorizontalGroup(
            jPanelAuthorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rsButtonAuthorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(rsButtonAuthorClear, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAuthorButtonLayout.setVerticalGroup(
            jPanelAuthorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAuthorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAuthorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rsButtonAuthorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rsButtonAuthorClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rsButtonAuthorAdd.getAccessibleContext().setAccessibleName("rsButtonAuthorAdd");

        javax.swing.GroupLayout jPanelAuthorLayout = new javax.swing.GroupLayout(jPanelAuthor);
        jPanelAuthor.setLayout(jPanelAuthorLayout);
        jPanelAuthorLayout.setHorizontalGroup(
            jPanelAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorLayout.createSequentialGroup()
                .addGroup(jPanelAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAuthorLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabelAuthorTitle))
                    .addGroup(jPanelAuthorLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanelAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelAuthorID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAuthorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAuthorPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAuthorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAuthorLayout.setVerticalGroup(
            jPanelAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuthorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelAuthorTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanelAuthorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanelAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanelAuthorPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAuthorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPaneAuthorTable, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAuthorTable, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAuthorID;
    private javax.swing.JLabel jLabelAuthorName;
    private javax.swing.JLabel jLabelAuthorPlace;
    private javax.swing.JLabel jLabelAuthorTitle;
    private javax.swing.JPanel jPanelAuthor;
    private javax.swing.JPanel jPanelAuthorButton;
    private javax.swing.JPanel jPanelAuthorID;
    private javax.swing.JPanel jPanelAuthorName;
    private javax.swing.JPanel jPanelAuthorPlace;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPaneAuthorTable;
    private app.bolivia.swing.JCTextField jTextFieldAuthorID;
    private app.bolivia.swing.JCTextField jTextFieldAuthorName;
    private app.bolivia.swing.JCTextField jTextFieldAuthorPlace;
    private rojeru_san.complementos.RSTableMetro rsAuthorTable;
    private rojeru_san.complementos.RSButtonHover rsButtonAuthorAdd;
    private rojeru_san.complementos.RSButtonHover rsButtonAuthorClear;
    // End of variables declaration//GEN-END:variables
}
