/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jpanel;

/**
 *
 * @author Admin
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        setBounds(0, 0,1288, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNoOfBook = new javax.swing.JPanel();
        jLabelNoOfBook = new javax.swing.JLabel();
        jLabelNoOfBookTitle = new javax.swing.JLabel();
        jLabelNoOfReaderTitle = new javax.swing.JLabel();
        jPanelNoOfReader = new javax.swing.JPanel();
        jLabelNoOfReader = new javax.swing.JLabel();
        jLabelReaderDetailsTitle = new javax.swing.JLabel();
        jLabelBookDetailsTitle = new javax.swing.JLabel();
        jPanelPieChart = new javax.swing.JPanel();
        jLabelDefautlerListTitle = new javax.swing.JLabel();
        jPanelDefautlerList = new javax.swing.JPanel();
        jLabelDefautlerList = new javax.swing.JLabel();
        jLabelIssuedBooksTitle = new javax.swing.JLabel();
        jPanelIssuedBooks = new javax.swing.JPanel();
        jLabelIssuedBooks = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1230, 730));
        setPreferredSize(new java.awt.Dimension(1230, 730));

        jPanelNoOfBook.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanelNoOfBook.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelNoOfBook.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBook.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelNoOfBook.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Book_Shelf_50px.png"))); // NOI18N
        jLabelNoOfBook.setText("10000");

        javax.swing.GroupLayout jPanelNoOfBookLayout = new javax.swing.GroupLayout(jPanelNoOfBook);
        jPanelNoOfBook.setLayout(jPanelNoOfBookLayout);
        jPanelNoOfBookLayout.setHorizontalGroup(
            jPanelNoOfBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfBook, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );
        jPanelNoOfBookLayout.setVerticalGroup(
            jPanelNoOfBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNoOfBookTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBookTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelNoOfBookTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBookTitle.setText("No Of Books");

        jLabelNoOfReaderTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReaderTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelNoOfReaderTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReaderTitle.setText("No Of Reader");

        jPanelNoOfReader.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));
        jPanelNoOfReader.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelNoOfReader.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReader.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelNoOfReader.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_People_50px.png"))); // NOI18N
        jLabelNoOfReader.setText("10000");

        javax.swing.GroupLayout jPanelNoOfReaderLayout = new javax.swing.GroupLayout(jPanelNoOfReader);
        jPanelNoOfReader.setLayout(jPanelNoOfReaderLayout);
        jPanelNoOfReaderLayout.setHorizontalGroup(
            jPanelNoOfReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfReaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfReader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNoOfReaderLayout.setVerticalGroup(
            jPanelNoOfReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfReaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfReader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelReaderDetailsTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelReaderDetailsTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelReaderDetailsTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelReaderDetailsTitle.setText("Reader Details");

        jLabelBookDetailsTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelBookDetailsTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelBookDetailsTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelBookDetailsTitle.setText("Book  Details");

        jPanelPieChart.setLayout(new java.awt.BorderLayout());

        jLabelDefautlerListTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerListTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelDefautlerListTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerListTitle.setText("Defaulter List");

        jPanelDefautlerList.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));
        jPanelDefautlerList.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelDefautlerList.setBackground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerList.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelDefautlerList.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        jLabelDefautlerList.setText("10000");

        javax.swing.GroupLayout jPanelDefautlerListLayout = new javax.swing.GroupLayout(jPanelDefautlerList);
        jPanelDefautlerList.setLayout(jPanelDefautlerListLayout);
        jPanelDefautlerListLayout.setHorizontalGroup(
            jPanelDefautlerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefautlerListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDefautlerList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDefautlerListLayout.setVerticalGroup(
            jPanelDefautlerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefautlerListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDefautlerList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelIssuedBooksTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooksTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelIssuedBooksTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooksTitle.setText("Issued Books");

        jPanelIssuedBooks.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanelIssuedBooks.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelIssuedBooks.setBackground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooks.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelIssuedBooks.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Sell_50px.png"))); // NOI18N
        jLabelIssuedBooks.setText("10000");

        javax.swing.GroupLayout jPanelIssuedBooksLayout = new javax.swing.GroupLayout(jPanelIssuedBooks);
        jPanelIssuedBooks.setLayout(jPanelIssuedBooksLayout);
        jPanelIssuedBooksLayout.setHorizontalGroup(
            jPanelIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIssuedBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIssuedBooks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIssuedBooksLayout.setVerticalGroup(
            jPanelIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIssuedBooksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIssuedBooks)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelNoOfBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140)
                            .addComponent(jLabelNoOfReaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)
                            .addComponent(jLabelIssuedBooksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addComponent(jLabelDefautlerListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanelNoOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120)
                            .addComponent(jPanelNoOfReader, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addComponent(jPanelIssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(110, 110, 110)
                            .addComponent(jPanelDefautlerList, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelReaderDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelBookDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(480, 480, 480)
                            .addComponent(jPanelPieChart, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelNoOfBookTitle)
                        .addComponent(jLabelNoOfReaderTitle)
                        .addComponent(jLabelIssuedBooksTitle)
                        .addComponent(jLabelDefautlerListTitle))
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelNoOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelNoOfReader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelIssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelDefautlerList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabelReaderDetailsTitle)
                            .addGap(204, 204, 204)
                            .addComponent(jLabelBookDetailsTitle))
                        .addComponent(jPanelPieChart, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBookDetailsTitle;
    private javax.swing.JLabel jLabelDefautlerList;
    private javax.swing.JLabel jLabelDefautlerListTitle;
    private javax.swing.JLabel jLabelIssuedBooks;
    private javax.swing.JLabel jLabelIssuedBooksTitle;
    private javax.swing.JLabel jLabelNoOfBook;
    private javax.swing.JLabel jLabelNoOfBookTitle;
    private javax.swing.JLabel jLabelNoOfReader;
    private javax.swing.JLabel jLabelNoOfReaderTitle;
    private javax.swing.JLabel jLabelReaderDetailsTitle;
    private javax.swing.JPanel jPanelDefautlerList;
    private javax.swing.JPanel jPanelIssuedBooks;
    private javax.swing.JPanel jPanelNoOfBook;
    private javax.swing.JPanel jPanelNoOfReader;
    private javax.swing.JPanel jPanelPieChart;
    // End of variables declaration//GEN-END:variables
}
