/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panel;

import Base.DIContainer;
import DTO.AccountDTO;
import Validate.OnlyNum;
import Validate.Validator;
import constant.AccountStringConstant;
import constant.AuthenStringConstant;
import constant.GeneralStringConstant;
import constant.TitleStringConstant;
import java.awt.Color;
import java.util.ArrayList;
import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.PlainDocument;

/**
 * This class is used for render Change password Panel
 *
 * @author Nguyễn Duy Phúc
 */
public class ChangePwdPanel extends javax.swing.JPanel {

    AccountDTO account = null;

    /**
     * Creates new form ManageAccount
     *
     * @param account Account of current user
     */
    public ChangePwdPanel(AccountDTO account) {
        initComponents();

        this.account = account;
        setBounds(0, 0, 1160, 740);
        initUI();
    }

    /**
     * Empty constructor
     */
    public ChangePwdPanel() {
        initComponents();

        setBounds(0, 0, 1160, 740);
        initUI();
    }

    /**
     * Add some first UI
     */
    private void initUI() {
        //Add place hoder in input fields
        lblPassword.setText(AccountStringConstant.ACCOUNT_PWD);
        lblNewPassword.setText(AccountStringConstant.ACCOUNT_NEW_PWD);
        lblReNewPassword.setText(AccountStringConstant.ACCOUNT_RE_NEW_PWD);
        jLabelTitle.setText(TitleStringConstant.CHANGE_PWD);
        btnUpdate.setText(TitleStringConstant.CHANGE_PWD.toUpperCase());
    }

    /**
     * This function use for validate input of user
     *
     * @return resutlt of validate
     */
    public boolean validateInput() {
        //Get string from UI
        String pwd = new String(txtPassword.getPassword());
        String newPwd = new String(txtNewPassword.getPassword());
        String reNewPwd = new String(txtReNewPassword.getPassword());

        //Validate input
        if (Validator.inputString("[a-zA-Z0-9!@#$%^&*\\.<>?\\-_+/]+", pwd)) {
            JOptionPane.showMessageDialog(this, AccountStringConstant.ACCOUNT_ERROR_PWD);
            return false;
        }
        if (!DIContainer.getAccountDAO().validatePass(account.getPassword(), pwd)) {
            JOptionPane.showMessageDialog(this, AccountStringConstant.ACCOUNT_ERROR_INCORRECT_PWD);
            return false;
        }
        if (Validator.inputString("[a-zA-Z0-9!@#$%^&*\\.<>?\\-_+/]+", newPwd)) {
            JOptionPane.showMessageDialog(this, AccountStringConstant.ACCOUNT_ERROR_NEW_PWD);
            return false;
        }
        if (Validator.inputString("[a-zA-Z0-9!@#$%^&*\\.<>?\\-_+/]+", newPwd)) {
            JOptionPane.showMessageDialog(this, AccountStringConstant.ACCOUNT_ERROR_PWD);
            return false;
        }
        if (!newPwd.equals(reNewPwd)) {
            JOptionPane.showMessageDialog(this, AccountStringConstant.ACCOUNT_ERROR_NOT_MATCH);
            return false;
        }
        return true;
    }

    /**
     * Update account with new password
     */
    private void updateAccount() {
        String newPwd = new String(txtNewPassword.getPassword());
        //Update account
        boolean result = DIContainer.getAccountDAO().changePass(account.getUsername(), newPwd);
        if (result) {
            JOptionPane.showMessageDialog(this, AccountStringConstant.ACCOUNT_UPDATE_SUCCESS);
        } else {
            JOptionPane.showMessageDialog(this, AccountStringConstant.ACCOUNT_UPDATE_FAIL);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        lblReNewPassword = new javax.swing.JLabel();
        txtReNewPassword = new javax.swing.JPasswordField();
        btnHidePass = new javax.swing.JLabel();
        btnShowPass = new javax.swing.JLabel();
        btnHideNewPass = new javax.swing.JLabel();
        btnShowNewPass = new javax.swing.JLabel();
        btnHideRePass = new javax.swing.JLabel();
        btnShowRePass = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));
        setMinimumSize(new java.awt.Dimension(1170, 630));
        setPreferredSize(new java.awt.Dimension(1170, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1170, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 51, 51));
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Edit_Property_50px.png"))); // NOI18N
        jLabelTitle.setText("Đổi mật khẩu");
        jPanel2.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 390, 5));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblPassword.setText("Mật khẩu");
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 490, 40));

        lblNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblNewPassword.setText("Mật khẩu");
        jPanel2.add(lblNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        txtNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtNewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));
        jPanel2.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 490, 40));

        lblReNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblReNewPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblReNewPassword.setText("Mật khẩu");
        jPanel2.add(lblReNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        txtReNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtReNewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));
        jPanel2.add(txtReNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 490, 40));

        btnHidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-closed-black-eye-32.png"))); // NOI18N
        btnHidePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHidePassMouseClicked(evt);
            }
        });
        jPanel2.add(btnHidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        btnShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-black-eye-32.png"))); // NOI18N
        btnShowPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPassMouseClicked(evt);
            }
        });
        jPanel2.add(btnShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        btnHideNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-closed-black-eye-32.png"))); // NOI18N
        btnHideNewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHideNewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideNewPassMouseClicked(evt);
            }
        });
        jPanel2.add(btnHideNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, -1, -1));

        btnShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-black-eye-32.png"))); // NOI18N
        btnShowNewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowNewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowNewPassMouseClicked(evt);
            }
        });
        jPanel2.add(btnShowNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, -1, -1));

        btnHideRePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-closed-black-eye-32.png"))); // NOI18N
        btnHideRePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHideRePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideRePassMouseClicked(evt);
            }
        });
        jPanel2.add(btnHideRePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, -1, -1));

        btnShowRePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-black-eye-32.png"))); // NOI18N
        btnShowRePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowRePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowRePassMouseClicked(evt);
            }
        });
        jPanel2.add(btnShowRePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 51, 51));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Lưu");
        btnUpdate.setBorder(null);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 320, 70));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHideRePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideRePassMouseClicked
        // TODO add your handling code here:
        btnShowRePass.setVisible(true);
        btnHideRePass.setVisible(false);

        txtReNewPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_btnHideRePassMouseClicked

    private void btnShowRePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowRePassMouseClicked
        // TODO add your handling code here:
        btnShowRePass.setVisible(false);
        btnHideRePass.setVisible(true);

        txtReNewPassword.setEchoChar('*');
    }//GEN-LAST:event_btnShowRePassMouseClicked

    private void btnHidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHidePassMouseClicked
        btnShowPass.setVisible(true);
        btnHidePass.setVisible(false);

        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_btnHidePassMouseClicked

    private void btnShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPassMouseClicked
        // TODO add your handling code here:
        btnShowPass.setVisible(false);
        btnHidePass.setVisible(true);

        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_btnShowPassMouseClicked

    private void btnShowNewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowNewPassMouseClicked
        // TODO add your handling code here:
        btnShowNewPass.setVisible(false);
        btnHideNewPass.setVisible(true);

        txtNewPassword.setEchoChar('*');
    }//GEN-LAST:event_btnShowNewPassMouseClicked

    private void btnHideNewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideNewPassMouseClicked
        // TODO add your handling code here:
        btnShowNewPass.setVisible(true);
        btnHideNewPass.setVisible(false);

        txtNewPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_btnHideNewPassMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        if (validateInput()) {
            updateAccount();
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHideNewPass;
    private javax.swing.JLabel btnHidePass;
    private javax.swing.JLabel btnHideRePass;
    private javax.swing.JLabel btnShowNewPass;
    private javax.swing.JLabel btnShowPass;
    private javax.swing.JLabel btnShowRePass;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblReNewPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtReNewPassword;
    // End of variables declaration//GEN-END:variables
}
