/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panel;

/**
 *
 * @author Admin
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        setBounds(0, 0,1170, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReaderDetailsTitle = new javax.swing.JLabel();
        jLabelBookDetailsTitle = new javax.swing.JLabel();
        jPanelPieChart = new javax.swing.JPanel();
        jLabelDefautlerListTitle = new javax.swing.JLabel();
        jPanelNoOfBook = new javax.swing.JPanel();
        jLabelNoOfBook = new javax.swing.JLabel();
        jPanelDefautlerList = new javax.swing.JPanel();
        jLabelDefautlerList = new javax.swing.JLabel();
        jLabelNoOfBookTitle = new javax.swing.JLabel();
        jLabelIssuedBooksTitle = new javax.swing.JLabel();
        jLabelNoOfReaderTitle = new javax.swing.JLabel();
        jPanelIssuedBooks = new javax.swing.JPanel();
        jLabelIssuedBooks = new javax.swing.JLabel();
        jPanelNoOfReader = new javax.swing.JPanel();
        jLabelNoOfReader = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1170, 630));

        jLabelReaderDetailsTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelReaderDetailsTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelReaderDetailsTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelReaderDetailsTitle.setText("Reader Details");

        jLabelBookDetailsTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelBookDetailsTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelBookDetailsTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelBookDetailsTitle.setText("Book  Details");

        jPanelPieChart.setLayout(new java.awt.BorderLayout());

        jLabelDefautlerListTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerListTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelDefautlerListTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerListTitle.setText("Defaulter List");

        jPanelNoOfBook.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanelNoOfBook.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelNoOfBook.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBook.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelNoOfBook.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBook.setText("10000");

        javax.swing.GroupLayout jPanelNoOfBookLayout = new javax.swing.GroupLayout(jPanelNoOfBook);
        jPanelNoOfBook.setLayout(jPanelNoOfBookLayout);
        jPanelNoOfBookLayout.setHorizontalGroup(
            jPanelNoOfBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfBook, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );
        jPanelNoOfBookLayout.setVerticalGroup(
            jPanelNoOfBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDefautlerList.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));
        jPanelDefautlerList.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelDefautlerList.setBackground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerList.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelDefautlerList.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDefautlerList.setText("10000");

        javax.swing.GroupLayout jPanelDefautlerListLayout = new javax.swing.GroupLayout(jPanelDefautlerList);
        jPanelDefautlerList.setLayout(jPanelDefautlerListLayout);
        jPanelDefautlerListLayout.setHorizontalGroup(
            jPanelDefautlerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefautlerListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDefautlerList)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelDefautlerListLayout.setVerticalGroup(
            jPanelDefautlerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefautlerListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDefautlerList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNoOfBookTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBookTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelNoOfBookTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfBookTitle.setText("No Of Books");

        jLabelIssuedBooksTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooksTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelIssuedBooksTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooksTitle.setText("Issued Books");

        jLabelNoOfReaderTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReaderTitle.setFont(new java.awt.Font("Segoe Pro", 1, 20)); // NOI18N
        jLabelNoOfReaderTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReaderTitle.setText("No Of Reader");

        jPanelIssuedBooks.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanelIssuedBooks.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelIssuedBooks.setBackground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooks.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelIssuedBooks.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIssuedBooks.setText("10000");

        javax.swing.GroupLayout jPanelIssuedBooksLayout = new javax.swing.GroupLayout(jPanelIssuedBooks);
        jPanelIssuedBooks.setLayout(jPanelIssuedBooksLayout);
        jPanelIssuedBooksLayout.setHorizontalGroup(
            jPanelIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIssuedBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIssuedBooks)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelIssuedBooksLayout.setVerticalGroup(
            jPanelIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIssuedBooksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIssuedBooks)
                .addGap(25, 25, 25))
        );

        jPanelNoOfReader.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));
        jPanelNoOfReader.setPreferredSize(new java.awt.Dimension(260, 1));

        jLabelNoOfReader.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReader.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        jLabelNoOfReader.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoOfReader.setText("10000");

        javax.swing.GroupLayout jPanelNoOfReaderLayout = new javax.swing.GroupLayout(jPanelNoOfReader);
        jPanelNoOfReader.setLayout(jPanelNoOfReaderLayout);
        jPanelNoOfReaderLayout.setHorizontalGroup(
            jPanelNoOfReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfReaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfReader)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelNoOfReaderLayout.setVerticalGroup(
            jPanelNoOfReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNoOfReaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNoOfReader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelReaderDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelNoOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNoOfBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelNoOfReader, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNoOfReaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelBookDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelIssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIssuedBooksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDefautlerListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelDefautlerList, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNoOfBookTitle)
                    .addComponent(jLabelNoOfReaderTitle)
                    .addComponent(jLabelIssuedBooksTitle)
                    .addComponent(jLabelDefautlerListTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelNoOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelNoOfReader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelIssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDefautlerList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelReaderDetailsTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanelPieChart, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabelBookDetailsTitle)
                        .addGap(0, 0, 0))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBookDetailsTitle;
    private javax.swing.JLabel jLabelDefautlerList;
    private javax.swing.JLabel jLabelDefautlerListTitle;
    private javax.swing.JLabel jLabelIssuedBooks;
    private javax.swing.JLabel jLabelIssuedBooksTitle;
    private javax.swing.JLabel jLabelNoOfBook;
    private javax.swing.JLabel jLabelNoOfBookTitle;
    private javax.swing.JLabel jLabelNoOfReader;
    private javax.swing.JLabel jLabelNoOfReaderTitle;
    private javax.swing.JLabel jLabelReaderDetailsTitle;
    private javax.swing.JPanel jPanelDefautlerList;
    private javax.swing.JPanel jPanelIssuedBooks;
    private javax.swing.JPanel jPanelNoOfBook;
    private javax.swing.JPanel jPanelNoOfReader;
    private javax.swing.JPanel jPanelPieChart;
    // End of variables declaration//GEN-END:variables
}
