/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panel;

import Base.DIContainer;
import DTO.AccountDTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asus
 */
public class ManageAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccount
     */
    public ManageAccount() {
        initComponents();
        setBounds(0, 0, 1288, 800);
        setAccountDetailToTable();
    }

    /**
     * To set account details to table
     */
    public void setAccountDetailToTable() {
        DefaultTableModel model = (DefaultTableModel) tblAccountDetail.getModel();
        ArrayList<AccountDTO> lAccounts = new ArrayList<AccountDTO>();

        lAccounts = DIContainer.getAccountDAO().findAll();
        lAccounts.forEach((AccountDTO account) -> {
            Object[] object = {account.getId(), account.getName(), account.getUsername(), account.getEmail(), account.getContact()};
            model.addRow(object);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtContact = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtName = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsername = new app.bolivia.swing.JCTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAccountId = new app.bolivia.swing.JCTextField();
        btnSignup = new rojerusan.RSMaterialButtonCircle();
        btnSignup1 = new rojerusan.RSMaterialButtonCircle();
        btnSignup2 = new rojerusan.RSMaterialButtonCircle();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccountDetail = new rojeru_san.complementos.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setBorder(new javax.swing.border.MatteBorder(null));
        setPreferredSize(new java.awt.Dimension(1240, 780));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContact.setBackground(new java.awt.Color(102, 102, 255));
        txtContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtContact.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtContact.setPlaceholder("Nhập số điện thoại");
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 270, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 50, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Số điện thoại");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 50, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        txtEmail.setBackground(new java.awt.Color(102, 102, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtEmail.setPlaceholder("Nhập email");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 270, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 50, 50));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Chủ tài khoản");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        txtName.setBackground(new java.awt.Color(102, 102, 255));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtName.setPlaceholder("Nhập tên của bạn");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 270, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 50, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tài khoản:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        txtUsername.setBackground(new java.awt.Color(102, 102, 255));
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtUsername.setPlaceholder("Nhập tài khoản");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 270, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, 50));

        txtAccountId.setEditable(false);
        txtAccountId.setBackground(new java.awt.Color(102, 102, 255));
        txtAccountId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtAccountId.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtAccountId.setPlaceholder("ID của bạn");
        jPanel1.add(txtAccountId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, 40));

        btnSignup.setBackground(new java.awt.Color(255, 51, 51));
        btnSignup.setText("Sửa");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 100, 70));

        btnSignup1.setBackground(new java.awt.Color(255, 51, 51));
        btnSignup1.setText("Thêm");
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 100, 70));

        btnSignup2.setBackground(new java.awt.Color(255, 51, 51));
        btnSignup2.setText("Xóa");
        btnSignup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, 100, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 830));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1, 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAccountDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tài khoản", "Chủ sở hữu", "Email", "Liên hệ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccountDetail.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tblAccountDetail.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tblAccountDetail.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tblAccountDetail.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N
        tblAccountDetail.setFuenteFilas(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tblAccountDetail.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tblAccountDetail.setFuenteHead(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        tblAccountDetail.setRowHeight(40);
        tblAccountDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAccountDetail);
        if (tblAccountDetail.getColumnModel().getColumnCount() > 0) {
            tblAccountDetail.getColumnModel().getColumn(0).setMinWidth(95);
            tblAccountDetail.getColumnModel().getColumn(0).setMaxWidth(95);
            tblAccountDetail.getColumnModel().getColumn(4).setMinWidth(120);
            tblAccountDetail.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 820, 370));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Edit_Property_50px.png"))); // NOI18N
        jLabel1.setText("Quản lý tài khoản");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 390, 5));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 850, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

    }//GEN-LAST:event_txtEmailFocusLost

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost

    }//GEN-LAST:event_txtUsernameFocusLost

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup1ActionPerformed

    private void btnSignup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup2ActionPerformed

    private void tblAccountDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountDetailMouseClicked
        int rowNo=tblAccountDetail.getSelectedRow();
        TableModel model=tblAccountDetail.getModel();
        
        txtAccountId.setText(model.getValueAt(rowNo,0).toString());
        txtName.setText(model.getValueAt(rowNo,1).toString());
        txtUsername.setText(model.getValueAt(rowNo,2).toString());
        txtEmail.setText(model.getValueAt(rowNo,3).toString());
        txtContact.setText(model.getValueAt(rowNo,4).toString());
    }//GEN-LAST:event_tblAccountDetailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btnSignup;
    private rojerusan.RSMaterialButtonCircle btnSignup1;
    private rojerusan.RSMaterialButtonCircle btnSignup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tblAccountDetail;
    private app.bolivia.swing.JCTextField txtAccountId;
    private app.bolivia.swing.JCTextField txtContact;
    private app.bolivia.swing.JCTextField txtEmail;
    private app.bolivia.swing.JCTextField txtName;
    private app.bolivia.swing.JCTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
